image:
  - Visual Studio 2022
  - Ubuntu2204
  - macos-monterey

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  matrix:
    # node.js
    - nodejs: "21"
    - nodejs: "20"
    - nodejs: "18"
    - nodejs: "16"

install:
  - sh: if [ "$APPVEYOR_BUILD_WORKER_IMAGE" = 'Ubuntu2204' ]; then sudo apt-get -qq update && sudo apt-get -y -qq install build-essential libgconf-2-4 python3 libglib2.0-dev; fi
  # - cmd: powershell .\appveyor.ps1  
  - cmd: powershell Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs) x64
  - sh: nvm ls
  - sh: nvm use $nodejs || nvm install $nodejs
  - cmd: node -v && npm -v && dotnet --version
  - sh: node -v && npm -v && dotnet --version
  - npm install -q

test_script:
  - cmd: node tools/test.js CI
  - cmd: SET EDGE_USE_CORECLR=1 & node tools/test.js CI
  - sh: EDGE_USE_CORECLR=1 node tools/test.js CI

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\test-results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path '.\test-results.xml'))
      Push-AppveyorArtifact (Resolve-Path '.\test-results.xml')
      Push-AppveyorArtifact (Resolve-Path '.\mochawesome.json')

skip_commits:
  files:
    - samples/*
    - stress/*
    - performance/*
    - .github/*
    - .github/**/*
    - '**/*.md'
    - '**/*.d.ts'
    - '**/*.bat'
    - '.travis.yml'
    - 'Dockerfile'
    - 'README.md'
    - 'LICENSE*'
    - '.idea/**'
    - '.vscode/**'
    - '.gitignore'
    - '*.bat'
    - '*.nuspec'
    - 'tools/nuget/*'
    - '.npmignore'
    - 'test/config.json'
    - 'test/config.json'
    - 'test/double'
    - 'appveyor_double.yml'

build: off

cache:
  - node_modules -> package.json