name: $(Date:yyMMdd)$(rev:-r)

trigger:
  batch: true
  branches:
    include:
      - resco

parameters:
- name: NodeVersion
  type: string
  default: 24.15.0
  displayName: Node version

- name: BuildConfiguration
  type: string
  default: Release
  displayName: Build Configuration
  values:
  - Release
  - Debug

resources:
  repositories:
  - repository: devops
    type: git
    name: devops
    ref: refs/heads/master

  - repository: nodejs
    endpoint: Resco GitHub
    name: nodejs/node
    ref: refs/tags/v${{ parameters.NodeVersion }}
    type: github

extends:
  template: build-edge-js.yml@devops
  parameters:
    NodeVersion: ${{ parameters.NodeVersion }}
    BuildConfiguration: ${{ parameters.BuildConfiguration }}
