name: 'Node.js build'
description: 'Node.js build'
inputs:
  node:
    description: 'Node version'
    required: true
  os:
    description: 'runs-on'
    required: false
    default: 'windows-2022'
   
runs:
  using: "composite"
  steps:

      - name: Setup env
        if: inputs.os == 'windows-2022'
        uses: ./.github/actions/setup-env
        with:
          node: 22
          os: ${{ inputs.os }}
          arch: 'x86'

      - name: Setup env
        if: inputs.os != 'windows-2022'
        uses: ./.github/actions/setup-env
        with:
          node: 22
          os: ${{ inputs.os }}

      - name: Get latest Node.js version for v${{ inputs.node }}
        id: node-test-version
        shell: bash
        run: |
          node tools/getVersionAction.js ${{ inputs.node }}
          echo "node-version=$(cat node.txt)" >> $GITHUB_OUTPUT
   
      - name: install node-gyp
        shell: bash
        run: npm i -g node-gyp

      - name: Create release folder
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            try {
              const fs = require('fs')
              if('${{ runner.os }}' == 'Windows' && '${{ inputs.os }}' == 'windows-2022'){
                if(${{ inputs.node }} <23){
                  fs.mkdirSync('release/win32/ia32/${{ inputs.node }}', { recursive: true });
                }
              }
              else if('${{ runner.os }}' == 'Windows' && '${{ inputs.os }}' == 'windows-2025'){
                fs.mkdirSync('release/win32/x64/${{ inputs.node }}', { recursive: true });
                if(${{ inputs.node }} >=20){
                  fs.mkdirSync('release/win32/arm64/${{ inputs.node }}', { recursive: true });
                }
              }
              else if('${{ runner.os }}' == 'macOS' && '${{ inputs.os }}' != 'macos-13'){
                fs.mkdirSync(`release/${process.platform}/arm64/${{ inputs.node }}`, { recursive: true });
              }
              else if('${{ runner.os }}' == 'macOS' && '${{ inputs.os }}' == 'macos-13'){
                fs.mkdirSync(`release/${process.platform}/x64/${{ inputs.node }}`, { recursive: true });
              }
            } catch(err) {
              core.error("Error creating release directory")
              core.setFailed(err)
            }

      - name: Create node.version file
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            try {
              const fs = require('fs')
              if('${{ runner.os }}' == 'Windows' && '${{ inputs.os }}' == 'windows-2022'){
                if(${{ inputs.node }} <23){
                  fs.writeFileSync('release/win32/ia32/${{ inputs.node }}/node.version', '${{ steps.node-test-version.outputs.node-version }}');
                }
              }
              else if('${{ runner.os }}' == 'Windows' && '${{ inputs.os }}' == 'windows-2025'){
                fs.writeFileSync('release/win32/x64/${{ inputs.node }}/node.version', '${{ steps.node-test-version.outputs.node-version }}');
                if(${{ inputs.node }} >=20){
                  fs.writeFileSync('release/win32/arm64/${{ inputs.node }}/node.version', '${{ steps.node-test-version.outputs.node-version }}');
                }
              }
              else if('${{ runner.os }}' == 'macOS' && '${{ inputs.os }}' == 'macos-15'){
                fs.writeFileSync(`release/${process.platform}/arm64/${{ inputs.node }}/node.version`, '${{ steps.node-test-version.outputs.node-version }}');
              }
              else if('${{ runner.os }}' == 'macOS' && '${{ inputs.os }}' == 'macos-13'){
                fs.writeFileSync(`release/${process.platform}/x64/${{ inputs.node }}/node.version`, '${{ steps.node-test-version.outputs.node-version }}');
              }
            } catch(err) {
              core.error("Error writing node.version file")
              core.setFailed(err)
            }

      - name: Cache node-gyp Windows
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        env:
          cache-name: cache-node-gyp
        with:
          path: ~\AppData\Local\node-gyp\Cache
          key: ${{ steps.node-test-version.outputs.node-version }}

      - name: Cache node-gyp macOS
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        env:
          cache-name: cache-node-gyp
        with:
          path: ~/Library/Caches/node-gyp
          key: '${{ inputs.os }}-${{ inputs.node}}'

      - name: Build ia32
        if: (inputs.os == 'windows-2022') && (inputs.node <23)
        uses: ./.github/actions/build
        with:
          node: ${{ steps.node-test-version.outputs.node-version }}
          node-major: ${{ inputs.node }}
          arch: 'ia32'

      - name: Build arm64
        if: inputs.os != 'macos-13' && inputs.os != 'windows-2022' && (inputs.node >=20 || inputs.os  == 'macos-15')
        uses: ./.github/actions/build
        with:
          node: ${{ steps.node-test-version.outputs.node-version }}
          node-major: ${{ inputs.node }}
          arch: 'arm64'

      - name: Build x64
        uses: ./.github/actions/build
        if: (inputs.os == 'windows-2025') || (inputs.os  == 'macos-13')
        with:
          node: ${{ steps.node-test-version.outputs.node-version }}
          node-major: ${{ inputs.node }}
          arch: 'x64'
    
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: inputs.os == 'windows-2025' && success()
        with:
          name: win32-edge-js-${{ inputs.node }}
          path: |
            release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: inputs.os == 'windows-2022' && success()
        with:
          name: win32-edge-js-ia32-${{ inputs.node }}
          path: |
            release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: inputs.os  == 'macos-15' && success()
        with:
          name: darwin-edge-js-arm64-${{ inputs.node }}
          path: |
            release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: inputs.os  == 'macos-13' && success()
        with:
          name: darwin-edge-js-x64-${{ inputs.node }}
          path: |
            release

