name: 'Test report'
description: 'Create test report'
inputs:
  name:
    description: 'name'
    required: false
    default: 'test-results'
  node:
    description: 'Node.js version'
    required: true
  os:
    description: 'runs-on'
    required: true

runs:
  using: "composite"
  steps:

    - name: Read mochawesome.json
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('mochawesome.json')
            var report = JSON.parse(jsonString);
            let stats = {
                passing: report.stats.passes,
                skipped: report.stats.pending,
                failures: report.stats.failures
            };
            core.notice(JSON.stringify(stats));
          } catch(err) {
            core.error("Error while reading or parsing mochawesome.json")
            core.setFailed(err)
          }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ${{ inputs.name }}-${{ inputs.os }}-${{ inputs.node }}
        path: |
          test-results.xml
          mochawesome.json
          mochawesome.html
          assets/

    # - name: Create test report
    #   uses: phoenix-actions/test-reporting@v15
    #   if: success()
    #   with:
    #     name: ${{ inputs.name }}-${{ inputs.os }}-node-${{ inputs.node }}
    #     fail-on-error: true
    #     path: mochawesome.json   # Path to test results
    #     reporter: mochawesome-json 
