name: Build

on:
  workflow_dispatch:
    inputs:
      build-version:
        description: 'Node.js version to build'
        required: true
        default: '20'
        type: choice
        options:
        - 16
        - 18
        - 20
        - 22
        - 23

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: windows-2022
    # outputs:
    #   node-version: ${{ steps.node-test-version.outputs.node-version }}
    strategy:
      fail-fast: true
       
    name: build node-${{ inputs.build-version }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Node ${{ inputs.build-version }}
        uses: ./.github/actions/build-node
        with:
          node: ${{ inputs.build-version }}
          os: ${{ runner.os }}

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [windows-2022]
      # fail-fast: false

    name: test ${{ matrix.os }}-node-${{ inputs.build-version }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          node: ${{ inputs.build-version }}
          os: ${{ matrix.os }}