name: Build All

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build-18:
    uses: ./.github/workflows/build.yml
    with:
      version: 18
      build-all: true

  build-20:
    uses: ./.github/workflows/build.yml
    with:
      version: 20
      build-all: true

  build-22:
    uses: ./.github/workflows/build.yml
    with:
      version: 22
      build-all: true

  build-24:
    uses: ./.github/workflows/build.yml
    with:
      version: 24
      build-all: true

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [build-18, build-20, build-22, build-24]
    timeout-minutes: 20

    name: upload artifcts
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        if: success()
        with:
          path: release
          pattern: win32-edge-js*

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: darwin-edge-js*

      - name: Upload artifacts
        uses: actions/upload-artifact/merge@v4
        if: success()
        with:
          name: edge-js
          pattern: '*edge-js*'
          delete-merged: true
  
