name: Test

on: 
  push:
    branches-ignore:
      - 'circleci'
    paths-ignore:
      - 'samples/*'
      - 'stress/*'
      - 'performance/*'
      - '.github/FUNDING.YML'
      - '.github/workflows/build.yml'
      - '**/*.md'
      - '**/*.d.ts'
      - '**/*.bat'
      - '.travis.yml'
      - 'Dockerfile'
      - '.gitconfig'
      - '.gitignore'
      - 'appveyor*.*'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - '*.bat'
      - '*.nuspec'
      - 'tools/nuget/*'
      - '.npmignore'
      - 'test/config.json'
      - 'test/double'
      - '.circleci'
      - '.circleci/*'
      - 'README.md'


env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true # required to setup CSC
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}-node-${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, ubuntu-22.04, windows-2022]
        # os: [macos-14, windows-2022]
        node: [18, 20, 22]

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          node: ${{ matrix.node }}
          os: ${{ matrix.os }}

      # - if: runner.os == 'macOS' && matrix.node == '16.x'
      #   name: Add missing packages for macOS NodeJs 16 
      #   run: |
      #     pip install setuptools

      - if: runner.os == 'Windows'
        name: Run Windows tests
        uses: ./.github/actions/test-windows
        with:
          node: ${{ matrix.node }}

      - if: runner.os == 'macOS' || runner.os == 'Linux'
        name: "Run macOS|Linux tests"
        run: node tools/test.js CI
        env:
          EDGE_USE_CORECLR: 1

      - name: Test report
        uses: ./.github/actions/create-test-report
        with:
          node: ${{ matrix.node }}
          os: ${{ matrix.os }}

